server:
  port: 8080

spring:
  application:
    name: evrental-backend
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB_NAME:vehicle_rental}}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:12345}
    hikari:
      maximum-pool-size: ${DB_POOL_SIZE:10}
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect
  cache:
    type: redis
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
#      username: ${REDIS_USERNAME:default}
#      password: ${REDIS_PASSWORD:}
      timeout: 2000ms
      time-to-live: 10m
#      ssl:
#        enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.${AWS_REGION}.amazonaws.com/${AWS_COGNITO_USER_POOL_ID}

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173,http://localhost:5174}

aws:
  cognito:
    clientId: ${AWS_COGNITO_CLIENT_ID}
    clientSecret: ${AWS_COGNITO_CLIENT_SECRET}
    userPoolId: ${AWS_COGNITO_USER_POOL_ID}
    domainPrefix: ${AWS_COGNITO_DOMAIN_PREFIX}
    region: ${AWS_REGION:ap-southeast-1}
    jwt-set-uri: https://cognito-idp.${aws.cognito.region}.amazonaws.com/${aws.cognito.userPoolId}/.well-known/jwks.json
    cognito-access-key: ${AWS_COGNITO_ACCESS_KEY}
    cognito-secret-key: ${AWS_COGNITO_SECRET_KEY}
    urlCallback: ${OAUTH2_CLIENT_COGNITO_CALLBACK:http://localhost:8080/api/auth/callback}
  s3:
    bucket-name: ${AWS_S3_BUCKET_NAME}
    s3-access-key: ${AWS_S3_ACCESS_KEY}
    s3-secret-key: ${AWS_S3_SECRET_KEY}
  location:
    cross-account-role-arn: ${ASSUME_LOCATION_ROLE_ACROSS_ACCOUNT_ARN}

oauth:
  state:
    ttl: 5
    prefix: "oauth:state:"

momo:
  partner-code: ${MOMO_PARTNER_CODE}
  access-key: ${MOMO_ACCESS_KEY}
  secret-key: ${MOMO_SECRET_KEY}
  endpoint: ${MOMO_ENDPOINT:https://test-payment.momo.vn/v2/gateway/api/create}
  redirect-url: ${MOMO_REDIRECT_URL:http://localhost:8080/payment/result}
  notify-url: ${MOMO_NOTIFY_URL:http://localhost:8080/api/payments/momo/callback}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    show-extensions: true
    show-common-extensions: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true



